games/urls.py
from django.urls import path
from .views import all_games, game_page


app_name = 'games'

urlpatterns = [
    path('all-games/', all_games, name='all_games'),
    path('<slug:game_slug>/', game_page, name='game_page'),
]

gamevot/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('users/', include('users.urls')),
    path('games/', include('games.urls')),
    path('producers/', include('producers.urls')),
    path('categories/', include('categories.urls')),
    path('reviews/', include('reviews.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

producers/urls.py
from django.urls import path
from .views import all_producers, producer_page


app_name = 'producers'

urlpatterns = [
    path('all-producers/', all_producers, name='all_producers_page'),
    path('<slug:producer_slug>/', producer_page, name='producer_page'),
]

users/urls.py
from django.urls import path
from .views import sign_up_page, login_page, logout_page, user_dashboard, change_avatar, change_password


app_name = 'users'

urlpatterns = [
    path('login/', login_page, name='login'),
    path('logout/', logout_page, name='logout'),
    path('sign-up/', sign_up_page, name='sign_up'),
    path('dashboard/', user_dashboard, name='dashboard'),
    path('avatar/', change_avatar, name='avatar'),
    path('password/', change_password, name='password'),
]

pages/templates/base_index.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Titillium+Web:wght@200&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    {% block meta_tags %}
        <meta name="description" content="Giant base of games reviews">
    {% endblock %}

    {% block title %}
        <title>GameVot.com</title>
    {% endblock %}

    {% block styles %}
    {% endblock %}

</head>
<body>
    {% block content %}
    {% endblock %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/fc38ca4837.js" crossorigin="anonymous"></script>
</body>
</html>

pages/templates/index.html
{% extends 'base_index.html' %}
{% load static %}

{% block title %}
    <title>GameVot.com | Home page</title>
{% endblock %}

{% block styles %}
    <style>
        :root {
          --jumbotron-padding-y: 3rem;
        }

        .jumbotron {
          padding-top: var(--jumbotron-padding-y);
          padding-bottom: var(--jumbotron-padding-y);
          margin-bottom: 0;
          background-color: #fff;
        }
        @media (min-width: 768px) {
          .jumbotron {
            padding-top: calc(var(--jumbotron-padding-y) * 2);
            padding-bottom: calc(var(--jumbotron-padding-y) * 2);
          }
        }

        .jumbotron p:last-child {
          margin-bottom: 0;
        }

        .jumbotron-heading {
          font-weight: 300;
        }

        .jumbotron .container {
          max-width: 40rem;
        }

        footer {
          padding-top: 3rem;
          padding-bottom: 3rem;
        }

        footer p {
          margin-bottom: .25rem;
        }

        .box-shadow { box-shadow: 0 .25rem .75rem rgba(0, 0, 0, .05); }
    </style>
{% endblock %}

{% block content %}
    {% include 'navbar.html' with categories=categories %}
    <main>
        <section class="jumbotron text-center">
            <div class="container">
                <h1 class="jumbotron-heading">Games and reviews database</h1>
                <p class="lead text-muted">Simple Web Application with reviews and games. List games, producers, see our ranking, read reviews. You can search game or producer and filter games by categories. Sign up and and leave a review!</p>
                <p>
                    <a href="{% url 'games:all_games' %}" class="btn btn-danger my-2">See our games database</a>
                </p>
            </div>
        </section>

        <div class="album mt-3 bg-light" style="margin-bottom: 100px;">
            <div class="container">
                <div class="row">
                    <h2 class="text-center my-3" style="font-family: 'Titillium Web', sans-serif;">Best games</h2>
                    {% for game in best_games %}
                        <div class="col-md-4">
                            <div class="card mb-4 box-shadow">
                                <img class="card-img-top" alt="{{ game.title }}" style="height: 225px; width: 100%; display: block;" src="{{ game.long_cover.url }}" data-holder-rendered="true">
                                <div class="card-body">
                                    <p class="card-text"><b>{{ game.title }}</b></p>
                                    <p class="card-text">{{ game.producer.name }}</p>
                                    <div class="d-flex justify-content-between align-items-center">
                                        <div class="btn-group">
                                            <a href="{% url 'games:game_page' game.slug %}"><button type="button" class="btn btn-sm btn-outline-secondary">Game</button></a>
                                            <a href="{% url 'producers:producer_page' game.producer.slug %}"><button type="button" class="btn btn-sm btn-outline-secondary">Producer</button></a>
                                        </div>
                                        <small class="text-muted">{{ game.avg_rate }}</small>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
                <div class="row">
                    <h2 class="text-center my-3" style="font-family: 'Titillium Web', sans-serif;">Last released</h2>
                    {% for game in new_games %}
                        <div class="col-md-4">
                            <div class="card mb-4 box-shadow">
                                <img class="card-img-top" alt="{{ game.title }}" style="height: 225px; width: 100%; display: block;" src="{{ game.long_cover.url }}" data-holder-rendered="true">
                                <div class="card-body">
                                    <p class="card-text"><b>{{ game.title }}</b></p>
                                    <p class="card-text">{{ game.producer.name }}</p>
                                    <div class="d-flex justify-content-between align-items-center">
                                        <div class="btn-group">
                                            <a href="{% url 'games:game_page' game.slug %}"><button type="button" class="btn btn-sm btn-outline-secondary">Game</button></a>
                                            <a href="{% url 'producers:producer_page' game.producer.slug %}"><button type="button" class="btn btn-sm btn-outline-secondary">Producer</button></a>
                                        </div>
                                        <small class="text-muted">{{ game.year }}</small>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
                <div class="row">
                    <h2 class="text-center my-3" style="font-family: 'Titillium Web', sans-serif;">Last added</h2>
                    {% for game in last_games %}
                        <div class="col-md-4">
                            <div class="card mb-4 box-shadow">
                                <img class="card-img-top" alt="{{ game.title }}" style="height: 225px; width: 100%; display: block;" src="{{ game.long_cover.url }}" data-holder-rendered="true">
                                <div class="card-body">
                                    <p class="card-text"><b>{{ game.title }}</b></p>
                                    <p class="card-text">{{ game.producer.name }}</p>
                                    <div class="d-flex justify-content-between align-items-center">
                                        <div class="btn-group">
                                            <a href="{% url 'games:game_page' game.slug %}"><button type="button" class="btn btn-sm btn-outline-secondary">Game</button></a>
                                            <a href="{% url 'producers:producer_page' game.producer.slug %}"><button type="button" class="btn btn-sm btn-outline-secondary">Producer</button></a>
                                        </div>
                                        <small class="text-muted">{{ game.created_at }}</small>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>

    </main>
{% endblock %}

pages/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-danger">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home_page' %}">GameVot.com</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <form method="post" enctype="multipart/form-data" class="d-flex" style="margin-left: 100px; width: 400px;">
                {% csrf_token %}
                <input class="form-control me-2" name="search" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-light" type="submit">Search</button>
            </form>
            <ul class="navbar-nav me-auto mb-2 mb-lg-0" style="margin-left: 100px;">
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="{% url 'home_page' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'games:all_games' %}">Games</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'producers:all_producers_page' %}">Producers</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">Categories</a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        {% for category in categories %}
                            <li><a href="/categories/{{ category.name }}/" class="dropdown-item">{{ category.name }}</a></li>
                        {% endfor %}
                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'rankings_page' %}" tabindex="-1" aria-disabled="true">Rankings</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#" tabindex="-1" aria-disabled="true">About</a>
                </li>
            </ul>

            {% if user.is_authenticated %}
                <a href="{% url 'users:logout' %}"><button class="btn btn-light" style="color: #dc3545">Logout</button></a>
                <a href="{% url 'users:dashboard' %}"><button class="btn btn-light" style="color: #dc3545; margin-left: 5px;">Profile</button></a>
            {% else %}
                <a href="{% url 'users:login' %}"><button class="btn btn-light" style="color: #dc3545">Login</button></a>
                <a href="{% url 'users:sign_up' %}"><button class="btn btn-light" style="color: #dc3545; margin-left: 5px;">Sign up</button></a>
            {% endif %}

        </div>
    </div>
</nav>

pages/templates/rankings.html
{% extends 'base_index.html' %}
{% load static %}

{% block title %}
    <title>GameVot.com | Rankings</title>
{% endblock %}

{% block content %}
    {% include 'navbar.html' with categories=categories %}
    <div class="container">
        <div class="row">
            <h1 class="text-center mt-4 mb-3" style="color: #dc3545;">Best games of GameVot.com database</h1>
            <hr>
        </div>
        <div class="row justify-content-center mt-3">
            {% for game in best_games %}
                <div class="card mt-3 text-center mx-3" style="width: 18rem; padding: 5px;">
                    <b class="my-1">{{ forloop.counter }}</b>
                    <img src="{{ game.cover.url }}" class="card-img-top" height="347px" alt="...">
                    <div class="card-body justify-content-center">
                        <h4 class="card-title">{{ game.title }}</h4>
                        <small style="display: block;">{{ game.producer.name }}</small>
                        <a href="{% url 'games:game_page' game.slug %}" class="btn btn-danger mt-3">Watch game</a>
                    </div>
                </div>
            {% endfor %}
        </div>
        <div class="row">
            <h1 class="text-center mt-4 mb-3" style="color: #dc3545;">Most popular games of GameVot.com database</h1>
            <hr>
        </div>
        <div class="row justify-content-center mt-3">
            {% for game in most_popular %}
                <div class="card mt-3 text-center mx-3" style="width: 18rem; padding: 5px;">
                    <b class="my-1">{{ forloop.counter }}</b>
                    <img src="{{ game.cover.url }}" class="card-img-top" height="347px" alt="...">
                    <div class="card-body justify-content-center">
                        <h4 class="card-title">{{ game.title }}</h4>
                        <small style="display: block;">{{ game.producer.name }}</small>
                        <a href="{% url 'games:game_page' game.slug %}" class="btn btn-danger mt-3">Watch game</a>
                    </div>
                </div>
            {% endfor %}
        </div>
        <div class="row">
            <h1 class="text-center mt-4 mb-3" style="color: #dc3545;">Most commented games of GameVot.com database</h1>
            <hr>
        </div>
        <div class="row justify-content-center mt-3" style="margin-bottom: 100px;">
            {% for game in most_commented %}
                <div class="card mt-3 text-center mx-3" style="width: 18rem; padding: 5px;">
                    <b class="my-1">{{ forloop.counter }}</b>
                    <img src="{{ game.cover.url }}" class="card-img-top" height="347px" alt="...">
                    <div class="card-body justify-content-center">
                        <h4 class="card-title">{{ game.title }}</h4>
                        <small style="display: block;">{{ game.producer.name }}</small>
                        <a href="{% url 'games:game_page' game.slug %}" class="btn btn-danger mt-3">Watch game</a>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

pages/templates/search_page.html
{% extends 'base_index.html' %}
{% load static %}

{% block content %}
    {% include 'navbar.html' with categories=categories %}
    <div class="container">
        <div class="row">
            <h1 class="text-center mt-4 mb-3" style="color: #dc3545;">Search results</h1>
            <hr>
        </div>
        <div class="row justify-content-center" style="margin-bottom: 100px;">
            {% if games_results|length == 0 and producers_results|length == 0 %}
                <h3 class="text-center">No results</h3>
            {% else %}
                {% for game in games_results %}
                    <div class="card mt-3 col-md-8">
                        <div class="row g-0">
                            <div class="col-md-4">
                                <img src="{{ game.cover.url }}" class="img-fluid rounded-start" alt="..." width="284px" height="350px">
                            </div>
                            <div class="col-md-8">
                                <div class="card-body">
                                    <h5 class="card-title">{{ game.title }} - {{ game.producer.name }}</h5>
                                    <p class="card-text">{{ game.description }}</p>
                                    <p class="card-text">
                                        {% for category in game.category.all %}
                                            <small class="text-muted">{{ category.name }}</small>
                                        {% endfor %}
                                        <a href="{% url 'games:game_page' game.slug %}"><button class="btn btn-danger" style="float: right;">Watch reviews</button></a>
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
                {% for producer in producers_results %}
                    <div class="card mt-3 col-md-8">
                        <div class="row g-0">
                            <div class="col-md-4">
                                <img src="{{ producer.logo.url }}" class="img-fluid rounded-start" alt="...">
                            </div>
                            <div class="col-md-8">
                                <div class="card-body">
                                    <h5 class="card-title">{{ producer.name }}</h5>
                                    <p class="card-text">{{ producer.description }}</p>
                                    <a href="{% url 'producers:producer_page' producer.slug %}"><button class="btn btn-danger" style="float: right;">Review producer</button></a>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% endif %}
        </div>
    </div>
{% endblock %}