games/urls.py
from django.urls import path
from .views import all_games, game_page


app_name = 'games'

urlpatterns = [
    path('all-games/', all_games, name='all_games'),
    path('<slug:game_slug>/', game_page, name='game_page'),
]

gamevot/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('users/', include('users.urls')),
    path('games/', include('games.urls')),
    path('producers/', include('producers.urls')),
    path('categories/', include('categories.urls')),
    path('reviews/', include('reviews.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reviews/urls.py
from django.urls import path
from .views import rate_game, edit_review, delete_review


app_name = 'reviews'

urlpatterns = [
    path('rate/<int:game_id>/<int:rate>/', rate_game, name='rate_game'),
    path('edit/<int:review_id>/', edit_review, name='edit_review'),
    path('delete/<int:review_id>/', delete_review, name='delete_review'),
]

games/models.py
from django.db import models
from django.utils.text import slugify
from django.utils import timezone
from producers.models import Producer
from categories.models import Category


class Game(models.Model):
    title = models.CharField(max_length=300, blank=False, null=False, unique=True)
    year = models.IntegerField(default=2000, blank=False, null=False)
    description = models.TextField(default="", blank=True, null=True)
    cover = models.ImageField(upload_to='game_covers', blank=True, null=True)
    long_cover = models.ImageField(upload_to='long_covers', blank=True, null=True)
    producer = models.ForeignKey(Producer, on_delete=models.DO_NOTHING, null=True, blank=True)
    category = models.ManyToManyField(Category, blank=True)
    slug = models.SlugField(null=True, editable=False)
    created_at = models.DateTimeField(default=timezone.now, editable=False)
    rates = models.IntegerField(default=0, editable=False, blank=True, null=False)
    reviews = models.IntegerField(default=0, editable=False, blank=True, null=False)
    avg_rate = models.DecimalField(decimal_places=2, max_digits=4, blank=True, null=True)

    def __str__(self):
        return self.title + ' ' + str(self.year)

    def save(self, *args, **kwargs):
        if not self.created_at:
            self.created_at = timezone.now()
            self.slug = slugify(self.title)

        return super(Game, self).save(*args, **kwargs)

games/views.py
from django.shortcuts import render, redirect
from .models import Game
from categories.models import Category
from reviews.models import Review, Rate
from reviews.forms import ReviewForm
from activities.models import Activity


def all_games(request):
    categories = Category.objects.all()

    if request.method == 'POST':
        wanted = request.POST.get('search')
        return redirect('search_page', wanted)

    games = Game.objects.all()

    context = {
        'games': games,
        'categories': categories,
    }

    return render(request, 'all_games.html', context=context)


def game_page(request, game_slug):
    categories = Category.objects.all()
    game = Game.objects.get(slug=game_slug)
    reviews = Review.objects.filter(game=game)
    rate_scale = [i for i in range(1, 11)]
    form = ReviewForm()

    if request.user.is_authenticated:
        user_rate = Rate.objects.filter(user=request.user, game=game)
        if not request.user.is_superuser:
            Activity.objects.create(visit=True, game_id=game.id, user=request.user)
    else:
        user_rate = None
        Activity.objects.create(visit=True, game_id=game.id)

    if request.method == 'POST':
        if request.POST.get('search') is not None:
            return redirect('search_page', request.POST.get('search'))

        form = ReviewForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            text = form.cleaned_data.get('text')
            Review.objects.create(user=request.user, game=game, text=text)
            return redirect('games:game_page', game.slug)

    context = {
        'game': game,
        'categories': categories,
        'reviews': reviews,
        'form': form,
        'rate_scale': rate_scale,
        'user_rate': user_rate,
    }

    return render(request, 'game.html', context=context)

games/templates/all_games.html
{% extends 'base_index.html' %}
{% load static %}

{% block title %}
    <title>GaveVot.com | All Games</title>
{% endblock %}

{% block content %}
    {% include 'navbar.html' with categories=categories %}
    <div class="container">
        <div class="row">
            <h1 class="text-center mt-4 mb-3" style="color: #dc3545;">GAMEVOT.COM GAMES DATABASE</h1>
            <hr>
        </div>
        <div class="row justify-content-center" style="margin-bottom: 100px;">

            {% for game in games %}
                <div class="card mt-3 col-md-8">
                    <div class="row g-0">
                        <div class="col-md-4">
                            <img src="{{ game.cover.url }}" class="img-fluid rounded-start" alt="..." width="284px" height="350px">
                        </div>
                        <div class="col-md-8">
                            <div class="card-body">
                                <h5 class="card-title">{{ game.title }} - {{ game.producer.name }}</h5>
                                <p class="card-text">{{ game.description }}</p>
                                <p class="card-text">
                                    {% for category in game.category.all %}
                                        <small class="text-muted">{{ category.name }}</small>
                                    {% endfor %}
                                    <a href="{% url 'games:game_page' game.slug %}"><button class="btn btn-danger" style="float: right;">Watch reviews</button></a>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        
        </div>
    </div>
{% endblock %}

games/templates/game.html
{% extends 'base_index.html' %}
{% load static %}

{% block title %}
    <title>GameVot.com | {{ game.title }}</title>
{% endblock %}

{% block styles %}
    <style>
        .star {
            text-decoration: none;
        }
        .del-rev {
            color: red;
            background: transparent;
            text-decoration: underline;
        }
        .del-rev:link {
            color: red;
            background: transparent;
            text-decoration: underline;
        }
        .del-rev:visited {
            color: red;
            background: transparent;
            text-decoration: underline;
        }
        .del-rev:hover {
            color: red;
            background: transparent;
            text-decoration: underline;
        }
        .del-rev:active {
            color: red;
            background: transparent;
            text-decoration: underline;
        }
    </style>
{% endblock %}

{% block content %}
    {% include 'navbar.html' with categories=categories %}
    <div class="container">
        <div class="row">
            <div class="card mt-5 col-md-12">
                <div class="row g-0">
                    <div class="col-md-4">
                        <img src="{{ game.cover.url }}" class="img-fluid rounded-start" alt="..." style="width: 300px; height: 400px;">
                    </div>
                    <div class="col-md-8">
                        <div class="card-body">
                            <h1 class="card-title text-center">{{ game.title }} - {{ game.producer.name }}</h1>
                            <p class="card-text mt-3">{{ game.description }}</p>
                            <h3 class="card-text" style="position: absolute;bottom: 0; margin-bottom: 35px;">{{ game.avg_rate }}</h3>
                            <p class="card-text">
                                {% for category in game.category.all %}
                                    <small class="text-muted" style="position: absolute; bottom: 0; right: 30px; margin-bottom: 10px;">{{ category.name }}</small>
                                {% endfor %}
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        {% if request.user.is_authenticated %}
            {% if user_rate %}
                <div class="d-flex justify-content-end mt-2">
                    {% for star in rate_scale %}
                        <a class="star {% if star <= user_rate.first.rate %}fas fa-star{% else %}far fa-star{% endif %}" href="{% url 'reviews:rate_game' game.id star %}"></a>
                    {% endfor %}
                </div>
            {% else %}
                <div class="d-flex justify-content-end mt-2">
                    {% for star in rate_scale %}
                        <a class="star far fa-star" href="{% url 'reviews:rate_game' game.id star %}"></a>
                    {% endfor %}
                </div>
            {% endif %}
        {% endif %}

        {% if request.user.is_authenticated %}
            <div class="row">
                <div class="col-md-9 mt-5 mx-auto">
                    <div class="card">
                        <div class="card-header">
                            <h5>Write your review</h5>
                        </div>
                        <div class="card-body">
                            <form method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                {% for field in form %}
                                    {{ field }}
                                {% endfor %}
                                <button class="btn btn-danger" style="margin-top: 20px; float: right; margin-right: 40px;" type="submit">Review</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        {% endif %}

        <div class="row" style="margin-bottom: 150px;">
            {% for review in reviews %}
                <div class="card col-md-8 mx-auto mt-4">
                    <div class="card-header">
                        {% if review.user.profile.avatar != '' %}
                            <img src="{{ review.user.profile.avatar.url }}" class="img-fluid rounded-circle" width="30px" height="30px" alt="..." style="margin-right: 5px;">
                        {% else %}
                            <img src="{% static 'img/user.png' %}" class="img-fluid rounded-circle" width="30px" height="30px" alt="..." style="margin-right: 5px;">
                        {% endif %}
                        <h5 style="display: inline;">{{ review.user.username }}</h5>
                        {% if review.user == request.user %}
                            <a href="{% url 'reviews:edit_review' review.id %}"><small style="margin-left: 10px;">Edit</small></a>
                            <a href="{% url 'reviews:delete_review' review.id %}"><small class="del-rev" style="margin-left: 3px;">Delete</small></a>
                        {% endif %}
                        <small style="float: right;">{{ review.created_at }}</small>
                    </div>
                    <div class="card-body">
                        <p class="card-text">{{ review.text }}</p>
                     </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}